### ISSUE TITLE
CANNOT LINK EXECUTABLE "play-audio": cannot locate symbol "EVP_MD_CTX_init" referenced by "/system/lib64/libsqlite.so"...

### ISSUE THREAD

**Issue by SDRausty** [termux/play-audio#12]
```
$ play-audio
CANNOT LINK EXECUTABLE "play-audio": cannot locate symbol "EVP_MD_CTX_init" referenced by "/system/lib64/libsqlite.so"...
$ uname -m
aarch64
```

**Comment by Grimler91** [comment]
What's your output of `termux-info`?

**Comment by SDRausty** [comment]
termux-info
Packages CPU architecture:
aarch64
Subscribed repositories:
# sources.list
deb https://termux.org/packages/ stable main
# game-repo (sources.list.d/game.list)
deb https://dl.bintray.com/grimler/game-packages-24 games stable
# science-repo (sources.list.d/science.list)
deb https://dl.bintray.com/grimler/science-packages-24 science stable
Updatable packages:
ecj/stable 4.14 all [upgradable from: 4.12-2]
Android version:
9
Kernel build information:
Linux localhost 4.4.111-17212492 #1 SMP PREEMPT Tue Nov 5 11:33:37 KST 2019 aarch64 Android
Device manufacturer:
samsung
Device model:
SM-A205U

**Comment by SDRausty** [comment]
@Grimler91 thank you for asking:

> What's your output of termux-info?

```
$ termux-info
Packages CPU architecture:
aarch64
Subscribed repositories:
# sources.list
deb https://termux.org/packages/ stable main
# game-repo (sources.list.d/game.list)
deb https://dl.bintray.com/grimler/game-packages-24 games stable
# science-repo (sources.list.d/science.list)
deb https://dl.bintray.com/grimler/science-packages-24 science stable
Updatable packages:
ecj/stable 4.14 all [upgradable from: 4.12-2]
Android version:
9
Kernel build information:
Linux localhost 4.4.111-17212492 #1 SMP PREEMPT Tue Nov 5 11:33:37 KST 2019 aarch64 Android
Device manufacturer:
samsung
Device model:
SM-A205U
```

SD storage is 512GB @present.  I am trying to get https://wae.github.io/WAE/ to run on my device once more.

**Comment by SDRausty** [comment]
@Grimler91 in reference to:

> What's your

`play-audio` was working, as was ` ecj`


Should an issue be opened for
`ecj/stable 4.14 all [upgradable from: 4.12-2]
Android version`
as well?  If so, where?

**Comment by SDRausty** [comment]
@Grimler91 in reference to:

> What's your

`play-audio` was working, as was ` ecj`

> https://github.com/termux/termux-packages/issues?q=is%3Aissue+ecj+exception

```
The following packages will be upgraded:
  ecj
.
.
.
Unpacking ecj (4.14) over (4.12-2) ...
Setting up ecj (4.14) ...
.
.
.
buildAPKs signal 160 received by build.one.bash in /data/data/com.termux/files/home/buildAPKs/sources/samples4/browseable/MidiSynth by build.one.bash.  More information in `/data/data/com.termux/files/home/buildAPKs/var/log/stnderr.in.dir.buildAPKs.log` file.                                                                                                                                   Running: grep -iC 4 ERROR /data/data/com.termux/files/home/buildAPKs/var/log/stnderr.in.dir.buildAPKs.log | tail                                            --                                                                            Warning: AndroidManifest.xml already defines versionCode (in http://schemas.android.com/apk/res/android); using existing value in manifest.                 Warning: AndroidManifest.xml already defines versionName (in http://schemas.android.com/apk/res/android); using existing value in manifest.                 Warning: AndroidManifest.xml already defines minSdkVersion (in http://schemas.android.com/apk/res/android); using existing value in manifest.               Warning: AndroidManifest.xml already defines targetSdkVersion (in http://schemas.android.com/apk/res/android); using existing value in manifest.            Exception in thread "main" java.lang.NoClassDefFoundError: Failed resolution of: Ljavax/lang/model/SourceVersion;                                                   at org.eclipse.jdt.internal.compiler.batch.FileSystem.<clinit>(FileSystem.java:180)                                                                         at org.eclipse.jdt.internal.compiler.batch.FileSystem.getClasspath(Unknown Source:0)                                                                        at org.eclipse.jdt.internal.compiler.util.Util.collectPlatformLibraries(Util.java:1248)                                                                     at org.eclipse.jdt.internal.compiler.util.Util.collectVMBootclasspath(Util.java:1161)
```

Should an issue be opened for
`ecj/stable 4.14 all [upgradable from: 4.12-2]
Android version`
as well? 

```
dpkg -i storage/shared/tdebs/ecj_4.12-2_all.deb
```

With https://github.com/WAE/au, this resolves ecj, but it is **not** available in the [stable](http://termux.net/dists/stable/) version.

**Comment by ghost** [comment]
Try `unset LD_LIBRARY_PATH` before running `play-audio`.

**Comment by SDRausty** [comment]
> `unset LD_LIBRARY_PATH` before running `play-audio`

```
$ unset LD_LIBRARY_PATH
$ play-audio
usage: play-audio [-s streamtype] [files]
```

Thank you @xeffyr 🎵 🎧 🎶

**Comment by ghost** [comment]
It is better to know why `LD_LIBRARY_PATH` was set if you are on Android 9.

On new Android OS versions you don't need this variable to run packages.

**Comment by SDRausty** [comment]
> It is better to know why LD_LIBRARY_PATH was set if you are on Android 9.

It is unknown why it is set at present as `play-audio` exhibits the same behavior in a new session:
```
$ play-audio
CANNOT LINK EXECUTABLE "play-audio": cannot locate symbol "EVP_MD_CTX_init" referenced by "/system/lib64/libsqlite.so"...
$ unset LD_LIBRARY_PATH
$ play-audio
usage: play-audio [-s streamtype] [files]
$ grep set .bash[_r][cp]*
$ grep -rw set $PREFIX/etc/
# no significant results
```
> was set if you are on Android 9.

```
$ getprop ro.build.version.release
9
```

```
$ export
declare -x ANDROID_DATA="/data"
declare -x ANDROID_ROOT="/system"
declare -x EXTERNAL_STORAGE="/sdcard"
declare -x HOME="/data/data/com.termux/files/home"
declare -x LANG="en_US.UTF-8"
declare -x LANGUAGE="en_US.UTF-8"
declare -x LC_ADDRESS="en_US.UTF-8"
declare -x LC_COLLATE="en_US.UTF-8"
declare -x LC_CTYPE="en_US.UTF-8"
declare -x LC_IDENTIFICATION="en_US.UTF-8"
declare -x LC_MEASUREMENT="en_US.UTF-8"
declare -x LC_MESSAGES="en_US.UTF-8"
declare -x LC_MONETARY="en_US.UTF-8"
declare -x LC_NAME="en_US.UTF-8"
declare -x LC_NUMERIC="en_US.UTF-8"
declare -x LC_PAPER="en_US.UTF-8"
declare -x LC_TELEPHONE="en_US.UTF-8"
declare -x LC_TIME="en_US.UTF-8"
declare -x LD_PRELOAD="/data/data/com.termux/files/usr/lib/libtermux-exec.so"
declare -x OLDPWD
declare -x PATH="/data/data/com.termux/files/home/bin:/data/data/com.termux/files/usr/bin:/data/data/com.termux/files/usr/bin/applets"
declare -x PREFIX="/data/data/com.termux/files/usr"
declare -x PWD="/data/data/com.termux/files/home"
declare -x SHELL="/data/data/com.termux/files/usr/bin/bash"
declare -x SHLVL="1"
declare -x TERM="xterm-256color"
declare -x TMPDIR="/data/data/com.termux/files/usr/tmp"
```

**Comment by SDRausty** [comment]
Would you recommend adding `unset LD_LIBRARY_PATH` to `.bash_profile` on Android 9?

**Comment by ghost** [comment]
I would recommend to first check whether you are using latest version of Termux, i.e. v0.84.

**Comment by SDRausty** [comment]
> check whether you are using latest version of Termux, i.e. v0.84

I am using v0.75 and it will not upgrade to v0.84:
> App not installed.

Both APKs are from https://f-droid.org/en/packages/com.termux/

I intend to study this https://wiki.termux.com/wiki/Backing_up_Termux page again with the hope of reinstalling Termux to upgrade it.  Adding ` unset LD_LIBRARY_PATH ` to ` .bash_profile ` on Android 9 with Termux v0.75 appears to be working okay.

**Comment by SDRausty** [comment]
> reinstalling Termux to upgrade it

I would just like to simply build termux on smartphone in Termux with this command:

[` $ ~/buildAPKs/build.github.bash termux `](https://github.com/BuildAPKs/buildAPKs.github/blob/master/build.github.bash)

Which gives:
```
$ grep ^termux ~/buildAPKs/opt/db/BNAMES
termux 20191224 20128086 236 12 4 com.termux.terminal.apk com.termux.failsafe.apk com.termux.styling.apk com.example.termuxam.apk
```
Suggestions on expediting this request are welcome https://github.com/BuildAPKs/buildAPKs/issues here.  Thank you to those who have contributed thus far in making APKs work as well as they do: 

  * com.termux.terminal.apk
  * com.termux.failsafe.apk
  * com.termux.styling.apk
  * com.example.termuxam.apk
