### ISSUE TITLE
Compiling from Termux?

### ISSUE THREAD

**Issue by PaulBatchelor** [termux/play-audio#2]
Is it possible to compile this from Termux directly? I have tried doing so, but I get a ton of "undefined reference" errors from libraries in /system/lib.

Ultimately, I would like to use OpenSL to build and run little realtime audio apps on my android device.

Thanks,

-P

**Comment by nonnymoose** [comment]
Here are the errors on my device:

[script.txt](https://github.com/termux/play-audio/files/1185066/script.txt)

**Comment by SDRausty** [comment]
Trying to build `play-audio` in Termux:💪
```
$ gcl https://github.com/termux/play-audio
Cloning into 'play-audio'...
remote: Counting objects: 23, done.
remote: Total 23 (delta 0), reused 0 (delta 0), pack-reused 23
Unpacking objects: 100% (23/23), done.
$ cd play-audio/
$ l
total 40
drwx------  3 u0_a93 u0_a93 4096 Aug 26 18:33 .
drwx------ 12 u0_a93 u0_a93 4096 Aug 26 18:33 ..
drwx------  7 u0_a93 u0_a93 4096 Aug 26 18:33 .git
-rw-------  1 u0_a93 u0_a93   11 Aug 26 18:33 .gitignore
-rw-------  1 u0_a93 u0_a93  448 Aug 26 18:33 Makefile
-rw-------  1 u0_a93 u0_a93  244 Aug 26 18:33 README.md
-rw-------  1 u0_a93 u0_a93  689 Aug 26 18:33 play-audio.1
-rw-------  1 u0_a93 u0_a93 9189 Aug 26 18:33 play-audio.cpp
$ make
g++ -Wall -Wextra -Werror -std=c++14 -fno-exceptions  -lOpenSLES  play-audio.cpp   -o play-audio
/data/data/com.termux/files/usr/bin/ld: warning: libqc-opt.so, needed by /system/lib64/libskia.so, not found (try using -rpath or -rpath-link)
.
.
.
clang-4.0: error: linker command failed with exit code 1 (use -v to see invocation)
make: *** [<builtin>: play-audio] Error 1
$
```
![screenshot_20170826-191916](https://user-images.githubusercontent.com/27742457/29745827-89c17d4e-8a93-11e7-83bb-a7c4e864e8af.png)

Complete `make` output👍 at https://sdrausty.github.io/logs/make-play-audio.txt 
and at https://github.com/sdrausty/sdrausty.github.io/blob/master/logs/make-play-audio.md
also at https://sdrausty.github.io/logs/make-play-audio.html
and https://sdrausty.github.io/logs/make-play-audio

Numbering the lines has almost always failed, even though numerous attempts connected to a few of the above links with `cat -n` in Termux, with GitHub... Locally the files are numbered 'till tail, upon consecutive attempt. Uploading cuts file numbering at 99 once published? Is anyone else having problems with `cat -n` in Termux, and/or subsequently uploading numbered files to github.com or any other  Termux anomalies?

**Comment by MkfsSion** [comment]
Add "-rpath=/system/lib"(in aarch64 add -rpath=/system/lib64) to LDFLAGS would fix this problem.

**Comment by ghost** [comment]
As written above, thats fixable by linker flag "-rpath=/system/lib". That's because play-audio requires complete NDK sysroot which is not available in Termux.

Just change makefile LDFLAGS to:
```
LDFLAGS += -lOpenSLES -Wl,-rpath=/system/lib
```
Samsung devices may require different line:
```
LDFLAGS += -lOpenSLES -Wl,-rpath=/system/lib -Wl,-rpath=/system/vendor/lib
```
Of course, if device is 64-bit, you will have to use `/system/lib64` and `/system/vendor/lib64`.

Another problem you can encounter is that you can't use "play-audio" without wrapper. See how Termux package does it: https://github.com/termux/termux-packages/blob/master/packages/play-audio/build.sh.

```
#!/data/data/com.termux/files/usr/bin/sh
# Avoid linker errors due to libOpenSLES.so:
LD_PRELOAD=/data/data/com.termux/files/usr/lib/libc++_shared.so LD_LIBRARY_PATH= exec /data/data/com.termux/files/usr/bin/play-audio "$@"
```

**Comment by PaulBatchelor** [comment]
Thanks for all the help folks! Will try this out in a few days.

**Comment by Cvar1984** [comment]
> As written above, thats fixable by linker flag "-rpath=/system/lib". That's because play-audio requires complete NDK sysroot which is not available in Termux.
> 
> Just change makefile LDFLAGS to:
> 
> ```
> LDFLAGS += -lOpenSLES -Wl,-rpath=/system/lib
> ```
> 
> Samsung devices may require different line:
> 
> ```
> LDFLAGS += -lOpenSLES -Wl,-rpath=/system/lib -Wl,-rpath=/system/vendor/lib
> ```
> 
> Of course, if device is 64-bit, you will have to use `/system/lib64` and `/system/vendor/lib64`.
> 
> Another problem you can encounter is that you can't use "play-audio" without wrapper. See how Termux package does it: https://github.com/termux/termux-packages/blob/master/packages/play-audio/build.sh.
> 
> ```
> #!/data/data/com.termux/files/usr/bin/sh
> # Avoid linker errors due to libOpenSLES.so:
> LD_PRELOAD=/data/data/com.termux/files/usr/lib/libc++_shared.so LD_LIBRARY_PATH= exec /data/data/com.termux/files/usr/bin/play-audio "$@"
> ```

I got same problem
```sh
u0_a194@localhost:~$ g++ play-audio.cpp -Wall -Wextra -Werror -std=c++14 -fno-exceptions -lOpenSLES -Wl,-rpath=/system/lib64
/data/data/com.termux/files/usr/bin/aarch64-linux-android-ld: /system/lib64/libmedia.so: undefined reference to `ucnv_close_58'
```
