### ISSUE TITLE
how to have play-audio play lazy 8 loop?

### ISSUE THREAD

**Issue by SDRausty** [termux/play-audio#5]
how to have play-audio play lazy 8 loop?

**Comment by fornwall** [comment]
Sorry - could you clarify what you want to do :)?

**Comment by sdrausty** [comment]
Yes of course. Can you modify play-audio to repeat songs with a --repeat option please. 
Thanks for making play-audio btw. It's so easy to use and the fact it can work in the background is great 😀

**Comment by SDRausty** [comment]
Yes of course. Lazy 8 = infinity. Can you modify play-audio to repeat songs with a --repeat-forever option please. Or is there some simple shorthand to pipe a song to play-audio in such fashion?

Actually `play-audio --loop #times file.name` would be a more elegant solution than --repeat-forever.

Thanks for making play-audio btw. It's so easy to use; And the fact it can work in the background is great 😀
 
🎼 https://wiki.termux.com/wiki/DVR

**Comment by SDRausty** [comment]
I felt that I was overlooking something really simple when posting; And I was. 
```
$ while true; do play-audio a.mp4; done
```
This does what I was seeking. Plays the file over and over = trance music from one song in Termux 💪 on your smartphone.
