### ISSUE TITLE
Library not found

### ISSUE THREAD

**Issue by rubikitch** [termux/play-audio#6]
I got an error when 
    $ play-audio foo.mp3
    CANNOT LINK EXECUTABLE DEPENDENCIES: library "libc++_shared.so" not found

**Comment by fornwall** [comment]
Can you try updating to latest package versions with `pkg up` and see if it works after that?

**Comment by rubikitch** [comment]
Still does not work in Android 5.1.1 (HUAWEI PLE-701L).

**Comment by ghost** [comment]
Is this issue still actual ?

Library "libc++_shared.so" is part of core package "libc++" which is undeletable and should present on all Termux installations.
