### ISSUE TITLE
Start at time request

### ISSUE THREAD

**Issue by bit-garden** [termux/play-audio#7]
I know there's an effort to get pulse audio working in the meantime, but if we can get this one option, a wrapper can be written to make a media player with this function. 

I was thinking something like `play-audio +1:39 somefile.mp3`

I would program it myself, but I don't have a computer to sit at and I saw there are errors compiling the player in Termux.

**Comment by SDRausty** [comment]
@bit-garden Have you experienced `play-audio` infinite loop in device?

**Comment by bit-garden** [comment]
@sdrausty No I haven't. I don't understand the relevance though.
