### ISSUE TITLE
how to change volume

### ISSUE THREAD

**Issue by sant527** [termux/play-audio#8]
In my android phone the default volume steps are 15. Can i finer control volumne using play-audio. Or is there any package which can control volume easily from command line and more precisely

**Comment by ghost** [comment]
Program "play-audio" plays sound over OpenSLES so volume is managed by Android.

> there any package which can control volume easily from command line

What you are looking is a [Termux:API](https://wiki.termux.com/wiki/Termux:API).

**Comment by khansaad1275** [comment]
I am using this command 
**termux-volume music 15** 
and it's not giving error but also changing nothing.
what am I doing wrong?
